base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'base'

urlpatterns = [
    path('', views.home, name="home"),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.update_user_profile, name='update-profile'),
    path('register/', views.create_user, name="register"),
    path('login', views.login_user, name="login"),
    path('google/', views.google_login, name='google-login'),
    path('logout/', views.logout_user, name="logout"),
    path('password_reset/done',
         auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"),
         name="password-reset-done"),
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password-reset-confirm.html"),
         name="password-reset-confirm"),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html")),
    path('password_reset', views.password_reset_request, name='password-reset'),
    path('password_change', auth_views.PasswordChangeView.as_view(template_name="accounts/password_change.html"),
         name="password-change"),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name="accounts/password_change_complete.html"),
         name="password-change-done"),
    path('verification/message', views.user_verification_request, name='user-verification-request'),
    path('verification/<uidb64>/<token>', views.user_verification, name='account-verification'),
    path('verification/resend', views.resend_user_verification, name='resend-verification'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('', include('django.contrib.auth.urls')),
    # path('', include('allauth.urls'))
]

templates/home/edit_profile.html
{% extends 'layouts/base.html' %}

{% block title %}
    Edit Profile
{% endblock %}

{% block content %}
    <div class="container mt-3">
        <h1 class="h4" style="color: #00EAC2">Update Profile</h1>
        <div class="row">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'includes/form.html' with form=user_form %}
                {% include 'includes/form.html' with form=user_profile_form %}
                <button class="btn" type="submit" style="background-color: #00EAC2">Edit</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/home/home.html
{% extends 'layouts/base.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <div class="container">
        {% if user.is_authenticated %}
            <h1>you are logged in as {{ request.user.get_full_name }}</h1>
        {% else %}
            <h1>You have to login to access resources</h1>
        {% endif %}

    </div>
{% endblock %}

templates/home/profile.html
{% extends 'layouts/base.html' %}
{% block title %}
    User Profile
{% endblock %}
{% block content %}

    {% if request.user.is_authenticated %}
        <div class="container mt-3">
            {% for message in messages %}
                <div class="alert alert-success">
                    <a class="close" href="#" data-dismiss="alert">×</a>
                    {{ message }}
                </div>
            {% endfor %}

            <div class="d-flex justify-content-center align-items-center">
                <div class="col-md-4 col-sm-6">
                    <img src="{{ profile.image_url }}" alt="Admin"
                         class="rounded-circle" width="150">
                </div>
                <div class="col-md-4 col-sm-6">
                    <p></p>
                    <h4>{{ profile.user.get_full_name }}</h4>
                    <p>{{ profile.user.email }}</p>
                </div>
                <div class="col-md-4 col-sm-6">
                    <a class="btn me-2" style="background-color: #00EAC2"
                       href="{% url 'base:password-change' %}">Change Password
                    </a>
                    <a class="btn" style="background-color: #00EAC2" href="{% url 'base:update-profile' %}">Edit
                        Info</a>
                </div>
            </div>
        </div>
    {% else %}
        <div class="container mt-3">
            <p>You are not logged in. To view resource you have to <a href="{% url 'base:login' %}">login</a></p>
        </div>
    {% endif %}
{% endblock %}