base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'base'

urlpatterns = [
    path('', views.home, name="home"),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.update_user_profile, name='update-profile'),
    path('register/', views.create_user, name="register"),
    path('login', views.login_user, name="login"),
    path('google/', views.google_login, name='google-login'),
    path('logout/', views.logout_user, name="logout"),
    path('password_reset/done',
         auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"),
         name="password-reset-done"),
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password-reset-confirm.html"),
         name="password-reset-confirm"),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html")),
    path('password_reset', views.password_reset_request, name='password-reset'),
    path('password_change', auth_views.PasswordChangeView.as_view(template_name="accounts/password_change.html"),
         name="password-change"),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name="accounts/password_change_complete.html"),
         name="password-change-done"),
    path('verification/message', views.user_verification_request, name='user-verification-request'),
    path('verification/<uidb64>/<token>', views.user_verification, name='account-verification'),
    path('verification/resend', views.resend_user_verification, name='resend-verification'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('', include('django.contrib.auth.urls')),
    # path('', include('allauth.urls'))
]

templates/accounts/account_verification_completed.html
{% extends "layouts/base.html" %}
{% block title %}
    Account verification completed.
{% endblock %}

{% block content %}

    <div class="container mt-3">
        <h1 class="h3">Account has been verified.</h1>
        <hr>
        <p>Thank you for your email confirmation. Now you can login to your account</p>
        <a href="{% url 'base:login' %}" class="btn btn-primary">Log in</a>
    </div>

{% endblock %}

templates/accounts/account_verification_email.html
{% autoescape off %}

    Hello {{ user.name }}

    You registered an account on [customer portal], before being able to use your account you need to verify that this is your email address by clicking below link:

    {{ protocol }}://{{ domain }}{% url 'base:account-verification' uidb64=uid token=token %}

    Bashar Arif, Privateye

{% endautoescape %}

templates/accounts/account_verification_request.html
{% extends "layouts/base.html" %}
{% block title %}
    Account verification.
{% endblock %}

{% block content %}

    <div class="container mt-3">
        <h1 class="h3">Please confirm your email address.</h1>
        <hr>
        <p>You need confirm your email address. A verification email has been sent to {{ email }}</p>

    </div>

{% endblock %}

templates/accounts/log-in.html
{% extends 'layouts/base.html' %}
{% block title %}
    Log In
{% endblock %}
{% block content %}
    <div class="container col-xl-10 col-xxl-8 px-4 py-5">
        <div class="row align-items-center g-lg-5 py-5">
            <div class="col-lg-7 text-center text-lg-start">
                <img src="/static/assets/img/login.jpg" alt="login" width="500">
            </div>
            <div class="col-md-10 mx-auto col-lg-5">
                {% for message in messages %}
                    <div class="alert alert-success">
                        <a class="close" href="#" data-dismiss="alert">×</a>
                        {{ message }}
                        {% if message.tags == 'warning' %}
                            <a class="" href="{% url 'base:resend-verification' %}">Resend email.</a>
                        {% endif %}
                    </div>
                {% endfor %}

                <form class="p-4 p-md-5  rounded-3" method="POST">
                    {% csrf_token %}
                    <div class="form-floating mb-3">
                        <input type="email" name="email" class="form-control" id="floatingInput"
                               placeholder="name@example.com">
                        <label for="floatingInput">Email address</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" name="password" class="form-control" id="floatingPassword"
                               placeholder="Password">
                        <label for="floatingPassword">Password</label>
                    </div>
                    <div class="checkbox mb-3">
                        <label>
                            <input type="checkbox" value="remember-me"> Remember me
                        </label>
                    </div>
                    <button class="w-100 btn btn-lg border-0 mb-3" type="submit"
                            style="background-color: #00EAC2">Sign in
                    </button>
                    <p><a href="{% url 'base:password-reset' %}" style="color: #00EAC2">Forgot Password?</a></p>

                    <p>Create new account sign up <a href="{% url 'base:register' %}" style="color: #00EAC2">here</a>
                    </p>
                    <hr class="my-4">
                    <small class="text-muted">By clicking Sign up, you agree to the terms of use.</small>
                    <a href="{% url 'base:google-login' %}">Google Login</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/accounts/password-reset-confirm.html
{% extends "layouts/base.html" %}

{% block title %}
    Password Reset Confirm
{% endblock %}

{% block content %}

    <!--Password Reset Confirm-->
    <div class="container p-5">
        <h2 class="font-weight-bold mt-3" style="color: #00EAC2">Password Reset Confirm</h2>
        <hr>
        <p>Please enter your new password.</p>
        <form method="POST">
            {% csrf_token %}
            {% include 'includes/form.html' with form=form %}
            <button class="btn" type="submit" style="background-color: #00EAC2">Reset password</button>
        </form>
    </div>

{% endblock %}

templates/accounts/password_change.html
{% extends 'layouts/base.html' %}
{% block title %}
    Password Change
{% endblock %}
{% block content %}
    <div class="container mt-3">
        <h1 class="h3" style="color: #00EAC2">Change Password</h1>
        <hr>
        <form method="post">
            {% csrf_token %}
            {% include 'includes/form.html' with form=form row=1 %}
            <button class="btn" type="submit" style="background-color: #00EAC2">Save changes</button>
        </form>
    </div>
{% endblock %}

templates/accounts/password_change_complete.html
{% extends 'layouts/base.html' %}
{% block title %}
    Password Change Completed
{% endblock %}
{% block content %}
    <div class="container">
        <p>Your password has been changed.</p>
    </div>
{% endblock %}

templates/accounts/password_reset_complete.html
{% extends "layouts/base.html" %}
{% block title %}
    Password Reset Completed
{% endblock %}

{% block content %}

    <!--Password Reset Complete-->
    <div class="container mt-3">
        <h1 class="h3">Password reset complete</h1>
        <hr>
        <p>Your password has been set. You may go ahead and log in now.</p>
        <a href="{% url 'base:login' %}" class="btn btn-primary">Log in</a>
    </div>

{% endblock %}

templates/accounts/password_reset_done.html
{% extends 'layouts/base.html' %}
{% block title %}
    Password Reset Done
{% endblock %}
{% block content %}

    <div class="container mt-3">
        <h1 class="h3" style="color: #00EAC2">Password reset email sent</h1>
        <hr>

        <p>We've emailed you instructions for setting your password, if an account exists with the email you entered.
            You should receive them shortly.<br>If you don't receive an email, please make sure you've entered the
            address you registered with, and check your spam folder.</p>
    </div>

{% endblock %}

templates/accounts/resend_verification.html
{% extends "layouts/base.html" %}
{% block title %}
    Your account is not verified.
{% endblock %}

{% block content %}

    <div class="container mt-3">
        <h1 class="h3">Account Verification warning!</h1>
        <hr>
        <p>Check email to verify your account.</p>
        <a href="{% url 'base:login' %}" class="btn btn-primary">Resend</a>
    </div>

{% endblock %}

templates/accounts/reset-password.html
{% extends 'layouts/base.html' %}

{% block title %}
    Password Reset
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <h2 class="font-weight-bold mt-3" style="color: #00EAC2">Reset Password</h2>
            <hr>
            <p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new
                one.</p>
            <div class="col-md-6 col-sm-12">
                <form method="POST">
                    {% csrf_token %}
                    {% include 'includes/form.html' with form=password_reset_form %}
                    <button class="btn" type="submit" style="background-color: #00EAC2">Send email</button>
                </form>
            </div>
            <div class="col-md-6 col-sm-12">
                <img src="/static/assets/img/forgot_password.svg" width="500" alt="forgot-password">
            </div>

        </div>
    </div>

{% endblock %}

templates/accounts/sign-up.html
{% extends 'layouts/base.html' %}

{% block title %}
    Sign Up
{% endblock %}

{% block content %}
    <div class="container mt-3">
        <div class="row">
            <h1 class="h3 mb-2" style="color: #00EAC2">Create account</h1>
            <hr>
            <div class="col-md-6 col-sm-6">
                <form class="rounded-3" action="" enctype="multipart/form-data"
                      method="POST">
                    {% csrf_token %}
                    {% include 'includes/form.html' with form=form row=1 %}
                    <button class="btn" type="submit" style="background-color: #00EAC2">Sign Up</button>
                    <p class="mt-3">Already hae and account please <a href="{% url 'base:login' %}"
                                                                      style="color: #00EAC2">login</a></p>
                    <a href="{% url 'base:google-login' %}">Google Login</a>
                </form>
            </div>
            <div class="col-md-6 col-sm-12 d-flex justify-content-center">
                <img src="/static/assets/img/sign-up.svg" alt="sign-up" width="500">
            </div>

        </div>
    </div>
{% endblock %}