base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'base'

urlpatterns = [
    path('', views.home, name="home"),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.update_user_profile, name='update-profile'),
    path('register/', views.create_user, name="register"),
    path('login', views.login_user, name="login"),
    path('google/', views.google_login, name='google-login'),
    path('logout/', views.logout_user, name="logout"),
    path('password_reset/done',
         auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"),
         name="password-reset-done"),
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password-reset-confirm.html"),
         name="password-reset-confirm"),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html")),
    path('password_reset', views.password_reset_request, name='password-reset'),
    path('password_change', auth_views.PasswordChangeView.as_view(template_name="accounts/password_change.html"),
         name="password-change"),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name="accounts/password_change_complete.html"),
         name="password-change-done"),
    path('verification/message', views.user_verification_request, name='user-verification-request'),
    path('verification/<uidb64>/<token>', views.user_verification, name='account-verification'),
    path('verification/resend', views.resend_user_verification, name='resend-verification'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('', include('django.contrib.auth.urls')),
    # path('', include('allauth.urls'))
]

templates/includes/form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
{% endfor %}
{{ form.name.errors }}

{% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
            {{ error }}
        {% endfor %}
    </div>

{% endif %}

<div class="row">
    {% for field in form.visible_fields %}

        <div class="
            {% if row == 1 %}col-12
             {% elif row == 3 %} col-sm-6
            {% else %}col-md-6
            {% endif %}"
        >
            <div class="form-group mb-2">

                {{ field.label_tag }}

                {% if form.is_bound %}
                    {% if field.errors %}
                        {% render_field field class="form-control is-invalid" %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field field class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field field class="form-control  form-control-lg mb-4" %}

                {% endif %}

                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}

            </div>
        </div>
    {% endfor %}
</div>

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light border-bottom">
    <div class="container">
        <a class="navbar-brand" href="{% url 'base:home' %}" style="color: #00EAC2">Authentication</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="">Home</a>
                </li>
            </ul>
            <li class="nav-item dropdown" style="list-style-type: none">
                {% if user.is_authenticated %}

                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button"
                       aria-expanded="false">
                        <img class="rounded-circle"
                             src="{{ user.userprofile.image_url }}" width="20"
                             height="20"
                             alt="{{ user.first_name }}">
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li><a class="dropdown-item" href="{% url 'base:profile' %}">View
                            Profile</a>
                        </li>

                        <li><a class="dropdown-item" href="{% url 'base:logout' %}">Log Out</a></li>
                    </ul>

                {% else %}
                    <a class="btn border " href="{% url 'base:register' %}">Sign Up</a>

                    <a class="btn" href="{% url 'base:login' %}" style="background-color: #00EAC2">Log In</a>
                {% endif %}

            </li>

        </div>
    </div>
</nav>

templates/includes/scripts.html
<script src="/static/assets/plugins/bootstrap/js/bootstrap.js"></script>
<script>
    setTimeout(function () {
        if ($('#msg').length > 0) {
            $('#msg').remove();
        }
    }, 2000)
</script>